services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost-cert.pem:/etc/nginx/localhost-cert.pem:ro,z
      - ./localhost-key.pem:/etc/nginx/localhost-key.pem:ro,z
    depends_on:
      - backend
      - frontend

  backend:
    container_name: backend
    environment:
      - IS_DEV_MODE=1
      - LINE_REDIRECT_URI=https://localhost/api/auth/callback
      - FRONTEND_BASE_URI=https://localhost
    env_file:
      - .env
    build: ./backend
    expose:
      - "8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend:/app
      - /app/.venv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      #develop:
      #  watch:
      #    - action: sync
      #      path: ./backend
      #      target: /app
      #      ignore:
      #        - .venv/
      #    - action: rebuild
      #      path: ./backend/pyproject.toml

  frontend:
    container_name: frontend
    build: ./frontend
    expose:
      - "3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    platform: linux/amd64
    image: mysql:8.0.27
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: dev
      TZ: Asia/Tokyo
    cap_add:
      - SYS_NICE
    volumes:
      - db-data:/var/lib/mysql

volumes:
  node_modules:
  db-data:
