services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend:/app
      - /app/.venv
      #develop:
      #  watch:
      #    - action: sync
      #      path: ./backend
      #      target: /app
      #      ignore:
      #        - .venv/
      #    - action: rebuild
      #      path: ./backend/pyproject.toml

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  node_modules:
