services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
        #    volumes:
        #      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  node_modules:
