[project]
name = "nft-nenga"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "requests>=2.32.3",
    "uvicorn>=0.32.0",
]
