name: Build frontend and Deploy to Firebase hosting

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install NPM packages
      run: npm ci

    - name: Build Vue app
      run: npm run build
      env:
        VITE_API_URL: ${{ vars.API_URL }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nft-with-kami-out
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: create out directory
        run: mkdir dist
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nft-with-kami-out
          path: ./dist
      - name: Display downloaded directory
        run: |
          ls
      - name: deploy to firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASAMI_1E0C2 }}'

